name: "Add a news item"
description: "Add an entry to the lab's news feed"
title: "[News] "
labels: ["news"]
body:
  - type: input
    id: date
    attributes:
      label: Date
      description: "Format YYYY-MM-DD"
      placeholder: "2026-08-26"
    validations:
      required: true
  - type: textarea
    id: text
    attributes:
      label: News text
      description: >
        Text of the news you would like to add. You may include links like
        `<a href='https://arxiv.org/abs/xxxx' target='_blank'>Paper Title</a> was accepted to VENUE '26. Congrats!`
        or reference internal paths (e.g. `/teaching/advanced-swe-ai/`). `target='_blank'` makes the link open in a new tab.
      placeholder: "<a href='https://arxiv.org/abs/xxxx' target='_blank'>Paper Title</a> was accepted to VENUE '26. Congrats!"
    validations:
      required: true
